CXX=g++
#CXXFLAGS= -std=c++11 -Wall
CXXFLAGS= -Wall
 
all: main.cpp
	$(CXX) $(CXXFLAGS) -o project1 main.cpp 
clean:
	rm -f project1
# http://stackoverflow.com/questions/16886591/how-do-i-enable-c11-in-gcc
